- components/com_emundus/controllers/files.php
- components/com_emundus/helpers/files.php
- components/com_emundus/views/application/view.raw.php
- libraries/emundus/pdf.php
This update makes preselected status (when configured in backoffice filt params)
> Fix preselected status filter confusion.

- plugins/fabrik_form/php/scripts/emundus-confirm_post.php
- plugins/fabrik_form/php/scripts/emundus-isApplicationCompleted.php
- templates/rt_afterburner2/html/com_users/registration/default.php
- templates/rt_afterburner2/html/com_users/registration/registration.xml
This update includes:
- Fix plugin redirecting to the wrong place when going through the final "sumbitting application" form.
- Registration form now displays firstname and last name above email and password, also removed a big blank space below the fieldset.
> Minor bugfix and UI improvement.

- modules/mod_emundus_applications/mod_emundus_applications.php
- modules/mod_emundus_checklist/mod_emundus_checklist.php
- modules/mod_emundusflow/mod_emundusflow.php
- modules/mod_emundusflow/tmpl/default.php
- plugins/fabrik_form/php/scripts/emundus-confirm_post.php
Bugfix:
- "Send application" links were using a static value that should be dynamic.
- Fixed plugin redirecting users to the payment page instead of submitting the file.
Improvements:
- Removed small send button, it was ugly and not very important.
> Critical bugfix update.

- components/com_emundus/controller.php
- components/com_emundus/controllers/users.php
- components/com_emundus/models/application.php
- modules/mod_emundus_applications/language/en-GB/en-GB.mod_emundus_applications.ini
- modules/mod_emundus_applications/language/fr-FR/fr-FR.mod_emundus_applications.ini
- modules/mod_emundus_applications/tmpl/nanomed.php
- modules/mod_emundus_applications/tmpl/ti.php
- plugins/fabrik_form/php/scripts/emundus-UGA_IRS-confirm_post.php
- plugins/fabrik_form/php/scripts/emundus-isApplicationSent.php
- plugins/fabrik_form/php/scripts/emundus-qcm.php
Bugfixes: 
- Editing a user now correctly displays errors if there are any.
- Fixed a case causing a false error message for upload of a first document.
- Fixed a Fabrik plugin.
Improvement:
- Added ability to print the application directly from the home page.
> Minor update

- components/com_emundus/controllers/users.php
- components/com_emundus/views/files/view.raw.php
- modules/mod_emundus_applications/tmpl/default.php
- modules/mod_emundus_applications/tmpl/nanomed.php
- modules/mod_emundus_applications/tmpl/ti.php
- modules/mod_emundus_campaign/tmpl/default.php
- plugins/fabrik_form/php/scripts/emundus-final_grade_ESA.php
Improvements: 
- Students are marked as admitted only if they have confirmed so for ESA scripts.
- Define rights menu now has default rights pre-checked.
- All files now have a print button.
Bugfix:
- Fixed date encoding.
- Fixed a bad regex causing users with a - in their email to be unable be created/edited.
> mid-january update.

- modules/mod_emundus_book_interview/tmpl/showInterview_form.php
- templates/rt_afterburner2/html/com_users/registration/default.php
This update requires the email to be added to the database (SQL scripts arent being autorun...) and the translation tag to be added in ovverrides
This update also adds to the time offset to booked interviews.
> Updates to automatic email sent on unsucessful user registration.

- components/com_emundus/models/files.php
This caused an error with keys in DB.
> Tagging files now adds the applicant_id as well

- components/com_emundus/models/evaluation.php
- components/com_emundus/models/profile.php
- modules/mod_emunduspanel/tmpl/default.php
Status filter was broken in Evaluations.
Also removed some warnings.
> Fixed a critical bug.

- components/com_emundus/views/export_select_columns/tmpl/default.php
- libraries/emundus/pdf.php
- libraries/emundus/pdf_admission.php
- libraries/emundus/pdf_decision.php
- libraries/emundus/pdf_evaluation.php
Added tags to pdf export and fixed a bug with XLS exports on evaluations.
> Export pdf

- components/com_emundus/helpers/files.php
- components/com_emundus/models/admission.php
- components/com_emundus/models/application.php
- components/com_emundus/models/calendar.php
- components/com_emundus/models/decision.php
- components/com_emundus/models/evaluation.php
- components/com_emundus/models/files.php
- components/com_emundus/views/files/view.raw.php
- modules/mod_emundus_book_interview/tmpl/form.php
Fixed some stuff dealing with ACL rights and filters as well as SEO URLs.
> Minor tweaks and improvements.

- components/com_emundus/emundus.php
- components/com_emundus/helpers/files.php
- components/com_emundus/language/en-GB/en-GB.com_emundus.ini
- components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
- media/com_emundus/js/em_files.js
> Bugfixes on the new filter styles and new buttons.

- components/com_emundus/views/application/tmpl/comment.php
- components/com_emundus/views/application/view.raw.php
When editing multiple comments things would behave strangely. This has been fixed.
> Fixed comment issues.

- components/com_fabrik/views/list/tmpl/search_engine/custom_css.php
Cannot override filter template without changing them for the entire application.
... If only $this->loadTemplate('filters') worked 😞
> Removed some CSS overrides from the custom search page template.

- components/com_emundus/controller.php
- components/com_emundus/models/application.php
- components/com_emundus/views/checklist/tmpl/application_form.php
- components/com_emundus/views/checklist/tmpl/attach_needed.php
- components/com_emundus/views/checklist/tmpl/opt_attach.php
- modules/mod_emundus_applications/tmpl/hesam.php
- modules/mod_emundus_checklist/tmpl/default.php
- plugins/system/emundusregistrationredirect/emundusregistrationredirect.php
- The registration redirect used JRoute which caused issues with SEF enabled.
- mod_emundus_applications was always redirecting to index.php on file open and delete, this has been fixed via some careful plumbing.
- The mod_applications HESAM template has been tweaked a little.
- Checklists now have a class, this makes it way easier to reach them in CSS.
> Bugfixes linked to redirections,  and minor templating improvements.

- modules/mod_emunduspanel/tmpl/default.php
Out with the old, and in with the... old
> Changed mod_emundus_panel to use jQuery instead of mootools syntax.

- components/com_emundus/controllers/cifre.php
- components/com_emundus/controllers/stats.php
- components/com_emundus/models/cifre.php
- components/com_emundus/models/stats.php
- modules/mod_emundus_graphs/mod_emundus_graphs.php
- modules/mod_emundus_graphs/tmpl/default.php
- templates/g5_helium/custom/modal_fix.css
Also improved the stats dashboard queries and some minor CSS.
> Improved CIFRE system for contacting people.

- components/com_emundus/controller.php
- components/com_emundus/controllers/cifre.php
- components/com_fabrik/views/details/tmpl/search_engine/default.php
- modules/mod_emundus_cifre_offers/tmpl/default.php
- Fixed the buttons not reacting to user input in the cifre offers module.
- Fixed upload redirect not getting itemId.
- Added new emails used for when an offer is cancelled or denied.
> Bugfixes and improvements

- components/com_emundus/controllers/cifre.php
- components/com_emundus/controllers/messages.php
- components/com_emundus/language/en-GB/en-GB.com_emundus.ini
- components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
- components/com_emundus/models/cifre.php
- components/com_emundus/models/jobs.php
- components/com_emundus/models/messages.php
- components/com_emundus/views/jobs/tmpl/default.php
- components/com_emundus/views/jobs/tmpl/default_filter.php
- components/com_emundus/views/message/tmpl/default.php
- components/com_emundus/views/messages/index.html
- components/com_emundus/views/messages/tmpl/chat.php
- components/com_emundus/views/messages/tmpl/default.php
- components/com_emundus/views/messages/tmpl/index.html
- components/com_emundus/views/messages/view.html.php
- components/com_emundus/views/messages/view.raw.php
- components/com_fabrik/views/details/tmpl/search_engine/default.php
- plugins/system/emundus_period/emundus_period.php
- plugins/system/emundus_period/emundus_period.xml
This update includes: 
- Added a textarea to the contact dialog allowing people to join a custom message.
- Added the beginnings of an internal messaging system.
- Fixed the eMundus period plugin and added a functionality to turn off redirection.
> General improvements to CIFRE system.

- administrator/components/com_admin/sql/updates/mysql/3.8.8-2018-06-26-em.sql
- components/com_emundus/views/messages/tmpl/default.php
- components/com_fabrik/views/details/tmpl/search_engine/default.php
- modules/mod_emundus_user_dropdown/tmpl/default.php
- plugins/fabrik_cron/migalFTP/forms/fields.xml
- plugins/fabrik_cron/migalFTP/language/en-GB/en-GB.plg_fabrik_cron_migalFTP.ini
- plugins/fabrik_cron/migalFTP/language/en-GB/en-GB.plg_fabrik_cron_migalFTP.sys.ini
- plugins/fabrik_cron/migalFTP/language/fr-FR/fr-FR.plg_fabrik_cron_migalFTP.ini
- plugins/fabrik_cron/migalFTP/language/fr-FR/fr-FR.plg_fabrik_cron_migalFTP.sys.ini
- plugins/fabrik_cron/migalFTP/migalFTP.php
- plugins/fabrik_cron/migalFTP/migalFTP.xml
- Fixed a bug with the logout link when SEF was enabled.
- Fixes a minor SQL issue.
> Minor bugfixes.

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
- plugins/fabrik_cron/migal_ftp/migal_ftp.php
In this pul request there are bug fixes and a front end fix on the cci formation details page
> CCI Formation details

- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
I promise this is the last one 😐
> 🐛🛠+🎨 First theme div display fix + links

- plugins/fabrik_cron/migal_ftp/migal_ftp.php
Residual pull request commits can safely be ignored.
> Gescof updates

- plugins/fabrik_cron/migal_ftp/migal_ftp.php
🎁 Added customization to product categories.
🎁 Added ability to choose which products to allow.
> 🎁 GesCOF improvements

- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
Got some json decoding going on in the background now, getting arrays of teaching unity in a program. 
The css is now in the back office, so calling the css file.
Getting the RAW values now. Like how i like my meat.
And that's nice
>  🖥♻+️🎨 Search engine list reconfig

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
- modules/mod_emundus_category_search/tmpl/default.php
Also fixed commented PHP tags throwing JS errors on the frontend.
> 🐛🛠 Fixed category links when backoffice value contained spaces and accents.

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
> 🎨 Intra and Sur-Mesure Options redesign

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
> Cci details css

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
Patchy, this is your first strike.
Don't rush it next time.
> Fixed minor errors.

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
NEW redesign on the cci search engine
> 🖥♻ Search engine rebuild 

- components/com_fabrik/views/details/tmpl/cci_search_engine/default.php
- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
New design for cci search engine
> Search engine rebuild

- components/com_emundus/controller.php
- plugins/fabrik_form/php/scripts/emundus-UGA-expert_agreement.php
This bug fixes a major issue causing evaluators to not be able to open documents.
> UGA expert rights fix

- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
- plugins/fabrik_cron/migal_ftp/migal_ftp.php
Added support for the GesCOF "publish online" option to toggle visibility of sessions.
> GesCOF publish tweak

- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
> Date filter fix on clear filters

- components/com_fabrik/views/list/tmpl/cci_search_engine/default.php
> Cccirs filter js patch

- components/com_emundus/helpers/files.php
- components/com_emundus/views/files/view.raw.php
- media/com_emundus/js/em_files.js
Improved the frontend load times and files view html.
> Code style and optimizations

- modules/mod_emundus_campaign/tmpl/default_g5.php
- modules/mod_emundus_graphs/tmpl/default.php
( saw there was a label tag for an input on the home page so just slipped that in there )
> Add buttons to consult the fabrik lists on dashboard

- components/com_emundus/controllers/files.php
- components/com_emundus/models/files.php
- plugins/fabrik_cron/migal_ftp/migal_ftp.php
This update includes some minor bug fixes and improvements to the GesCOF system.
> CCIRS improvements

- components/com_emundus/models/stats.php
- modules/mod_emundus_graphs/language/fr-FR/fr-FR.mod_emundus_graphs.ini
removed db->quoteName on select * and changed name for the file  button
> fix sql error on files graph

- plugins/fabrik_form/emundusisapplicationsent/emundusisapplicationsent.php
- plugins/fabrik_form/emundusisapplicationsent/emundusisapplicationsent.xml
- plugins/fabrik_form/emundusisapplicationsent/forms/fields.xml
- plugins/fabrik_form/emundusisapplicationsent/language/en-GB/en-GB.plg_fabrik_form_emundusisapplicationsent.ini
- plugins/fabrik_form/emundusisapplicationsent/language/en-GB/en-GB.plg_fabrik_form_emundusisapplicationsent.sys.ini
- plugins/fabrik_form/emundusisapplicationsent/language/fr-FR/fr-FR.plg_fabrik_form_emundusisapplicationsent.ini
- plugins/fabrik_form/emundusisapplicationsent/language/fr-FR/fr-FR.plg_fabrik_form_emundusisapplicationsent.sys.ini
- plugins/fabrik_form/emundussetprofile/emundussetprofile.php
- plugins/fabrik_form/emundussetprofile/emundussetprofile.xml
- plugins/fabrik_form/emundussetprofile/forms/fields.xml
- plugins/fabrik_form/emundussetprofile/language/en-GB/en-GB.plg_fabrik_form_emundussetprofile.ini
- plugins/fabrik_form/emundussetprofile/language/en-GB/en-GB.plg_fabrik_form_emundussetprofile.sys.ini
- plugins/fabrik_form/emundussetprofile/language/fr-FR/fr-FR.plg_fabrik_form_emundussetprofile.ini
- plugins/fabrik_form/emundussetprofile/language/fr-FR/fr-FR.plg_fabrik_form_emundussetprofile.sys.ini
- A generalized isApplicationSent plugin which now has a modifiable status.
- A new setProfile plugin which changes the user's profile if his file is a certain status.
> 2 new plugins

- administrator/components/com_emundus/emundus.xml
- administrator/components/com_emundus/views/panel/tmpl/default.php
- components/com_emundus/models/emails.php
- components/com_emundus/models/files.php
- components/com_emundus/views/checklist/tmpl/default.php
- media/com_emundus/css/emundus.css
- plugins/fabrik_form/emundusconfirmpost/emundusconfirmpost.php
- plugins/fabrik_form/emundusisapplicationsent/emundusisapplicationsent.php
- plugins/fabrik_form/php/scripts/emundus-confirm_post.php
- plugins/fabrik_form/php/scripts/emundus-isApplicationSent.php
Also added autoexport file sanitation.
> Added support for cascadingdropdowns in XLS export as well as general setFabrik function.

- components/com_emundus/controllers/messages.php
- components/com_emundus/helpers/list.php
- components/com_fabrik/views/details/tmpl/search_engine/default.php
- components/com_fabrik/views/list/tmpl/search_engine/default.php
> Added additional security to file uploads and added more info to the search engine.

- administrator/components/com_admin/sql/updates/mysql/3.9.1-2019-02-05-em.sql
- components/com_emundus/language/en-GB/en-GB.com_emundus.ini
- components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
- components/com_emundus/models/files.php
- components/com_emundus/views/admission/tmpl/data.php
- components/com_emundus/views/decision/tmpl/data.php
- components/com_emundus/views/evaluation/tmpl/data.php
- components/com_emundus/views/files/tmpl/data.php
- components/com_emundus/views/filesbystatus/tmpl/data.php
- media/com_emundus/css/emundus_files.css
This means we can make a user's profile change by switching one of his file's profiles.
>  Added ability to link a profile to a status

- components/com_emundus/controllers/files.php
- components/com_emundus/helpers/files.php
- components/com_emundus/models/evaluation.php
- components/com_emundus/models/files.php
- libraries/vendor/composer/autoload_psr4.php
- libraries/vendor/composer/autoload_static.php
- libraries/vendor/composer/installed.json
No radar object due to the fact that it does not work with the current PHPOffice ....
I fixed a bug preventing the generation of the PDF for one file though.
> Document generation improvements.

- components/com_fabrik/views/details/tmpl/hesam__details_demande/custom_css.php
- components/com_fabrik/views/details/tmpl/hesam__details_demande/default.php
- components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
- components/com_fabrik/views/details/tmpl/search_engine/default.php
Remove CO- for équipe
remove regions and departments from author part of details
> Add custom css to details_demande pdf

- components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
- components/com_fabrik/views/details/tmpl/hesam__details_demande/custom_css.php
- components/com_fabrik/views/details/tmpl/hesam__details_demande/default.php
- components/com_fabrik/views/details/tmpl/hesam_pdf_export/default.php
- components/com_fabrik/views/details/tmpl/search_engine/default.php
- components/com_fabrik/views/list/tmpl/search_engine/default.php
Added Sweet alert to details page
> Get Departments / Regions for acteurs publics ON list/details/pdf page

- components/com_emundus/controllers/cifre.php
- components/com_emundus/controllers/messages.php
- components/com_emundus/models/cifre.php
- components/com_emundus/models/messages.php
- components/com_emundus/views/messages/tmpl/chat.php
- components/com_emundus/views/messages/tmpl/default.php
- components/com_emundus/views/messages/view.html.php
- components/com_emundus/views/messages/view.raw.php
- modules/mod_emundus_cifre_offers/tmpl/default.php
Added interactive messages to the messaging system.
> Hesam message system improvements.

- components/com_emundus/controllers/messages.php
- components/com_emundus/models/cifre.php
- plugins/fabrik_cron/emundushesamrecap/emundushesamrecap.php
- plugins/fabrik_cron/emundushesamrecap/emundushesamrecap.xml
- plugins/fabrik_cron/emundushesamrecap/forms/fields.xml
- plugins/fabrik_cron/emundushesamrecap/language/en-GB/en-GB.plg_fabrik_cron_emundushesamrecap.ini
- plugins/fabrik_cron/emundushesamrecap/language/fr-FR/fr-FR.plg_fabrik_cron_emundushesamrecap.ini
- plugins/fabrik_cron/emundushesamrecap/language/fr-FR/fr-FR.plg_fabrik_cron_emundushesamrecap.sys.ini
A plugin which sends users the latest offers available for 1000Doctorant memebers via email.
> Added HESAM recap email plugin.

- modules/mod_emundus_user_dropdown/tmpl/mobile.php
- modules/mod_emunduspanel/language/en-GB/en-GB.mod_emunduspanel.ini
- modules/mod_emunduspanel/language/fr-FR/fr-FR.mod_emunduspanel.ini
- modules/mod_emunduspanel/mod_emunduspanel.php
- modules/mod_emunduspanel/mod_emunduspanel.xml
- modules/mod_emunduspanel/tmpl/default.php
Lean mode only shows things like the profile switcher and the menu icons based on context.
> Updated module/panel to have lean mode.

- components/com_emundus/controllers/messages.php
- components/com_emundus/models/users.php
- components/com_fabrik/views/list/tmpl/search_engine/default.php
send notification mail when user sends a message via messenger? New function to get a list of online users, so we only send this email if the receiver is offline
> HESAM - updates

- components/com_emundus/language/en-GB/en-GB.com_emundus.ini
- components/com_emundus/language/fr-FR/fr-FR.com_emundus.ini
- media/com_emundus/js/em_files.js
Fix james' application menu poop
> application menu

- components/com_emundus/models/application.php
- libraries/emundus/pdf.php
This reverts commit cecb5e58f574c97442a7cc60014c7a613e03d2c6.
> HOTFIX 3.9.14/20200204

- components/com_emundus/controllers/files.php
- media/com_emundus/js/em_files.js
…tBool to getVar as js  is sending boolean as a string on eval invite
> HOTFIX 6.9.15/20200323

- modules/mod_emundus_applications/tmpl/default.php
- modules/mod_emundus_applications/tmpl/esiea.php
> Build 6.9.15/20200408R2
